import type { Upgrade } from './types';

export const PROMPTS = [
  'AI에게 역할과 목표를 먼저 지정하고 출력 형식을 분명히 적는다.',
  '초안은 빠르게 만들고 부족한 조건을 다시 적어 모델을 더 세게 몰아붙인다.',
  '좋은 프롬프트는 맥락, 제약, 예시, 검증 기준을 한 번에 제공한다.',
  '모호한 답이 나오면 원하는 관점과 제외할 내용을 짧게 추가한다.',
  '문서를 작성하듯 생각을 정리하면 AI에게 줄 지시도 자연스럽게 선명해진다.',
  'The assistant should return concise steps, clear tradeoffs, and testable output.',
  '응답 형식이 중요할 때는 표, 목록, JSON처럼 원하는 구조를 직접 지정한다.',
  '먼저 독자를 정하고 그 사람이 바로 이해할 수 있는 용어만 남긴다.',
  '길어진 문장은 둘로 나누고 핵심 동사는 앞으로 당겨서 힘을 만든다.',
  '반례를 하나 넣으면 모델은 답변의 경계를 더 정확하게 잡는다.',
  '작업 전에 성공 기준을 적으면 결과물을 검토하는 시간이 줄어든다.',
  '원하는 톤이 있다면 친근하게, 단호하게, 실무적으로처럼 직접 말한다.',
  '중요한 제약은 마지막에 다시 적어 모델이 놓치지 않게 압박한다.',
  '자료가 부족할 때는 추측하지 말고 필요한 질문을 먼저 하라고 지시한다.',
  '출력은 짧게 시작하고 필요한 경우에만 근거와 대안을 덧붙인다.',
  '한 번에 완벽한 문장을 노리지 말고 구조, 논리, 표현 순서로 고친다.',
  '초안의 약한 부분을 표시하고 다음 입력에서 그 부분만 집중적으로 수정한다.',
  '예시는 하나보다 세 개가 좋고, 좋은 예시와 나쁜 예시를 섞으면 더 좋다.',
  '모델에게 역할을 맡겼다면 권한과 금지 행동도 같이 지정해야 한다.',
  '긴 문서 요약은 목적, 핵심 주장, 누락 위험, 다음 행동으로 나눈다.',
  '코드 요청에는 입력, 출력, 실패 조건, 테스트 방법을 함께 적는다.',
  '디자인 요청은 화면의 목적과 사용자가 가장 먼저 해야 할 일을 적는다.',
  '회의록을 정리할 때는 결정 사항과 담당자, 마감일을 먼저 뽑는다.',
  '비교 요청은 평가 기준을 먼저 정해야 답변이 취향 싸움으로 흐르지 않는다.',
  '모델이 장황해지면 세 문장 이하로 답하고 불확실한 부분만 표시하라 한다.',
  '문서 제목은 멋보다 검색 가능성과 다음 사람이 찾기 쉬운 표현이 중요하다.',
  '프롬프트는 명령문, 배경 정보, 출력 형식, 검증 기준의 순서가 안정적이다.',
  'AI에게 맡길 일과 사람이 직접 판단할 일을 구분하면 결과가 덜 흔들린다.',
  '수정 요청은 마음에 들지 않는다는 말보다 어떤 기준에서 빗나갔는지 적는다.',
  'A strong prompt says what to optimize for and what to ignore.',
  'Keep the task narrow, name the audience, and specify the final artifact.',
  'When the output matters, ask for assumptions, risks, and a final checklist.',
  '문장을 완성하면 모델은 경험치를 먹고 다음 초안을 더 빠르게 밀어붙인다.',
];

export const UPGRADE_POOL: Upgrade[] = [
  {
    id: 'xp-drip',
    name: '과잉 칭찬',
    description: '정확 입력으로 얻는 AI XP가 25% 증가합니다.',
    stat: 'xpMultiplier',
    amount: 0.25,
  },
  {
    id: 'draft-rush',
    name: '초안 가속',
    description: '과제 완성도 상승량이 18% 증가합니다.',
    stat: 'progressMultiplier',
    amount: 0.18,
  },
  {
    id: 'typo-buffer',
    name: '오타 완충',
    description: '오타가 나도 AI가 덜 삐걱거리며 보상을 조금 회복합니다.',
    stat: 'errorForgiveness',
    amount: 0.5,
  },
  {
    id: 'focus-coffee',
    name: '집중 커피',
    description: 'AI 집중도를 14 회복합니다.',
    stat: 'focus',
    amount: 14,
  },
];
